### ISSUE TITLE
Why this lib?

### ISSUE THREAD

**Issue by ccoVeille** [carapace-sh/carapace-selfupdate#1]
Did you consider these?

https://github.com/sanbornm/go-selfupdate
https://github.com/minio/selfupdate

Could you add a README?

**Comment by rsteube** [comment]
See https://github.com/orgs/carapace-sh/discussions/2554 .

> Did you consider these?
> 
> https://github.com/sanbornm/go-selfupdate
> https://github.com/minio/selfupdate

I've seen those, but I need something simpler and customized for https://github.com/carapace-sh/nightly.
Also, I'd like to avoid unnecessary dependencies.

> Could you add a README?

I will, this is still early development.

**Comment by ccoVeille** [comment]
Thanks
